server:
  port: 8080

spring:
  application:
    name: Gateway-Module-Service
  cloud:
    nacos:
      discovery:
        server-addr: 43.138.83.120:8848
    gateway:
      routes:
        - id: user_routes
          uri: http://localhost:8081
          predicates:
            - Path=/user/{api}/{token}/**,/superintendent/{api}/{token}/**,/team/{api}/{token}/**
        - id: activity_routes
          uri: http://localhost:8082
          predicates:
            - Path=/activity/{api}/{token}/**