server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://82.157.154.180:3306/bubbling?useUnicode=true&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: User-Module-Service
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.154.180:8848
  redis:
    host: localhost
    password: bubbling123456

mybatis:
  type-aliases-package: com.bubbling.pojo
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      bubbling:
        mapper: debug

tencent-cloud:
  secretId: AKID5yby4uSjjX5MM4WidGdjY6NO8bniMinc
  secretKey: Zy71e07yZuylIYYMvCDxQcXBYgW6PRCg