server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bubbling?useUnicode=true&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: User-Module-Service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 121.5.76.140
    password: bubbling123456

mybatis:
  type-aliases-package: com.bubbling.pojo
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      bubbling:
        mapper: debug
