server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bubbling?useUnicode=true&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Activity-Module-Service
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.154.180:8848

mybatis:
  type-aliases-package: com.bubbling.pojo
  mapper-locations: classpath:mapper/*.xml